# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 245393f773af48c09970e5d89925eeb35c4c04b2884833574181ed17f65438d7d7f18f20384022804e7e42755c5590740eb63bbe2de88cf5414578059bf53155

test:
  secret_key_base: f27173fd87044e515323b2631f70808313e31f807dba793050aecb47c99d7082e46da8f731fdc609bf47ed5e31a1d77e8d05e49150a44a51d41e37636227bca2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
